---
services:
  container-hoster:
    image: dockers.pinacono.com/hoster:latest
    container_name: container-hoster
    read_only: true
    mem_limit: 100M
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/hosts:/hosts
    tmpfs:
      - /tmp
    network_mode: none
    healthcheck:
      test: ["CMD", "/container-hoster", "--healthcheck"]
      interval: 30s
      timeout: 5s
      start_period: 15s
      retries: 3
    # environment:
    #   - CH_HOSTSFILE=./hosts
    #   - CH_INTERVAL=10s
    #   - CH_HOSTNAME_FROM_CONTAINERNAME=true
    #   - CH_HOSTNAME_FROM_CONTAINERHOSTNAME=true
    #   - CH_HOSTNAME_FROM_LABEL=false
    #   - CH_ONLY_LABELED_CONTAINERS=true
    #   - CH_NETWORK_REGEXP=.*
    #   - CH_LOG_EVENTS=false
    # labels:
    #   com.pinacoo.hoster.name: "my-container"
    #   com.pinacoo.hoster.enabled: "true"
